stories/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views 

import story1.urls as story1
import story4.urls as story4
import story5.urls as story5
import story6.urls as story6
import story7.urls as story7
import story8.urls as story8
import story9.urls as story9
import story10.urls as story10

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('story1/', include(story1, namespace='story1')),
    path('story4/', include(story4, namespace='story4')),
    path('story5/', include(story5, namespace='story5')),
    path('story6/', include(story6, namespace='story6')),
    path('story7/', include(story7, namespace="story7")),
    path('story8/', include(story8, namespace="story8")),
    path('story9/', include(story9, namespace="story9")),
    path('story10/', include(story10, namespace="story10"))
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name="index")
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.matkul, name='index'),
    path('details/<int:id>', views.details, name='details'),
    path('add/', views.addMatkul, name='add'),
    path('delete/<int:id>', views.delMatkul, name='del')
]

story5/models.py
from django.db import models
from django.utils import timezone
from datetime import date

# Create your models here.
class Matkul(models.Model):
    nama = models.CharField(max_length=50)
    dosen = models.CharField(max_length=50)
    sks = models.IntegerField()
    desc = models.TextField()
    sem = models.CharField(max_length=20)
    ruang = models.CharField(max_length=20)

    def __str__ (self):
        return self.nama

    class Meta: 
        verbose_name_plural = "Matkul"

class Tugas(models.Model): 
    nama = models.CharField(max_length=50)
    dl = models.DateTimeField()
    matkul = models.ForeignKey(Matkul, default=1, on_delete=models.CASCADE)

    def __str__ (self):
        return self.nama + " in " + self.matkul.nama

    class Meta:
        ordering = ["dl"]
        verbose_name_plural = "Tugas"

story5/forms.py
from django.forms import ModelForm, DateTimeInput, DateTimeField
from django.utils.translation import gettext_lazy as _

from .models import Matkul, Tugas

class MatkulForm(ModelForm): 
    class Meta: 
        model = Matkul
        fields = '__all__'

class TugasForm(ModelForm):
    class Meta: 
        model = Tugas
        fields = '__all__'
        labels = {
            'nama': _('Nama tugas'),
            'dl': _('Deadline'),
        }
        widgets = {
            'dl': DateTimeInput(attrs={'class': 'datetimepicker'}),
        }

story5/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.utils import timezone
from django.contrib import messages
from datetime import datetime

from .models import Matkul, Tugas
from .forms import MatkulForm, TugasForm


# Create your views here.
def matkul(request):
    matkul = Matkul.objects.all()

    return render(request, 'story5/matkul.html', {'matkul':matkul})

def details(request, id): 
    matkul = Matkul.objects.get(id=id)
    tugas = Tugas.objects.all().filter(matkul=matkul)

    form = TugasForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = TugasForm() 

    context = {
        'matkul':matkul, 
        'del':False, 
        'tugas':tugas, 
        'form':form,
    }    

    # tugas and deadlines
    tugasDL = []
    for tugas in context['tugas']:
        due = tugas.dl - timezone.now()
        tugasDL.append((tugas.nama, due.total_seconds(), tugas.dl))
    context['deadlines'] = tugasDL           

    return render(request, 'story5/details.html', context)

def addMatkul(request): 
    form = MatkulForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = MatkulForm()

    return render(request, 'story5/addMatkul.html', {'form':form})
 
def delMatkul(request, id):
    matkul = get_object_or_404(Matkul, id=id)

    if request.method == 'POST':
        matkul.delete()
        messages.success(request, 'Successfully deleted Mata Kuliah {}'.format(matkul.nama))
        return redirect('../')
    
    return render(request, 'story5/details.html', {'matkul':matkul, 'del':True})

templates/story5/addMatkul.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'story5.css' %}">
{% endblock %}

{% block title %} Add Mata Kuliah | Story5 {% endblock %}

{% block body %}
<h2 class="h2 text-center">Add Mata Kuliah</h2>

<div class="content my-4">
    <form method="POST">{% csrf_token %}
        <div class="d-flex flex-column flex-wrap">
                {{ form|crispy }} 
                <div class="btnwrapper d-flex align-items-center justify-content-between">
                    <a href="{% url 'story5:index' %}" class="btn btn-outline-secondary">Kembali</a>
                    <button class="btn btn-dark" type="submit" value="Save">Submit</button>                       
                </div>         
        </div>
    </form>
    
</div>
{% endblock %}

templates/story5/details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'story5.css' %}">
  <link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">

{% endblock %}

{% block title %} Details Mata Kuliah | Story5 {% endblock %}

{% block body %}
{% if del %}
<h2 class="h2 text-center"> Are you sure you want to delete {{matkul.nama}}?</h2>
{% else %}
    <h2 class="h2 text-center"> {{matkul.nama}} Details </h2>
{% endif %}


<div class="content d-flex justify-content center">
    <div class="card col-lg-6 col-md-8 col-sm-10" style="margin:2rem;">
        <div class="card-header text-center">
            {{matkul.nama}}
        </div>
        <div class="card-content" style="padding: 1rem;">
            <ul>
                <li><b>Dosen Pengajar   :</b> {{matkul.dosen}}</li>
                <li><b>SKS              :</b> {{matkul.sks}}</li>
                <li><b>Deskripsi        :</b> {{matkul.desc}}</li>
                <li><b>Semester         :</b> {{matkul.sem}}</li>
                <li><b>Ruang Kelas      :</b> {{matkul.ruang}}</li>
            </ul>
        <div class="card-action">
            <div class="float-right">
                {% if del %}
                    <form method="POST"> {% csrf_token %}
                    <button class="btn btn-danger" type="submit"><i class="fa fa-trash"></i></button>
                    <a href="{% url 'story5:index' %}" class="btn btn-dark">Kembali</a></form>
                {% else %}
                    <a href="{% url 'story5:index' %}" class="btn btn-dark">Kembali</a>
                {% endif %}
            </div>
        </div>
        </div>
    </div>

    {% if not del %}
    <h4 class="h4 text-center"> Daftar Tugas </h4>
    
    <div class="tugas-container d-flex flex-column col-lg-6 col-md-8 col-sm-10 mb-4">
        <ul class="list-group">
            {% if deadlines %}
            {% for tug in deadlines %}
            <li class="list-group-item" style="color: 
            {% if tug.1 < 0 %}
                lightcoral
            {% elif tug.1 < 86400 %}
                khaki
            {% elif tug.1 < 604800 %}
                lightgreen
            {% else %}
                powderblue
            {% endif %}
            ;">
                {{tug.0}}
                <div class="float-right"> {{tug.2|date:"jS M Y"}} </div>
            </li>
            {% endfor %}
            {% else %}
            <li class="list-group-item">
                You have no tugas right now.
            </li>
            {% endif %}
        </ul>
        
        <div class="card my-3">
            <div class="card-header text-center">
                Add Tugas
            </div>
            <div class="card-content">
                <form  action="{% url 'story5:details' id=matkul.id %}" method="POST">
                    {% csrf_token %}
                    {{ form.nama|as_crispy_field }}
                    {{ form.dl|as_crispy_field }}
                    <input type="hidden" value="{{matkul.id}}" name="matkul">
                    <button class="btn btn-dark float-right" type="submit" value="Save">Submit</button>
                </form>
            </div>            
        </div>
    </div> 
    {% endif %}   
</div>
{% endblock %}

{% block script %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
<script>
    $(function () {
      $(".datetimepicker").datetimepicker({
        format: 'Y-m-d H:i:s',
      });
    });
</script>
{% endblock %}

templates/story5/matkul.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'story5.css' %}">
{% endblock %}

{% block title %} Mata Kuliah | Story5 {% endblock %}

{% block heading %} 
<h1>Mata Kuliah | Story5</h1>
{% endblock %}

{% block body %}
<div class="content">
    <div class="matkul-container d-flex flex-column col-lg-6 col-md-8 col-sm-10">
        <a href="{% url 'story5:add' %}" class="btn btn-dark w-100" style="margin:1rem auto;">Add Mata Kuliah</a>

        <ul class="list-group">
            {% for matakuliah in matkul %}
            <li class="list-group-item d-flex align-items-center justify-content-between"> 
                <a href="{% url 'story5:details' id=matakuliah.id %}">{{matakuliah.nama}}</a>            
                <div class="btnwrapper">
                    <a href="{% url 'story5:details' id=matakuliah.id %}" class="btn btn-dark" >details</a> 
                    <a href="{% url 'story5:del' id=matakuliah.id %}" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}