stories/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views 

import story1.urls as story1
import story4.urls as story4
import story5.urls as story5
import story6.urls as story6
import story7.urls as story7
import story8.urls as story8
import story9.urls as story9
import story10.urls as story10

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('story1/', include(story1, namespace='story1')),
    path('story4/', include(story4, namespace='story4')),
    path('story5/', include(story5, namespace='story5')),
    path('story6/', include(story6, namespace='story6')),
    path('story7/', include(story7, namespace="story7")),
    path('story8/', include(story8, namespace="story8")),
    path('story9/', include(story9, namespace="story9")),
    path('story10/', include(story10, namespace="story10"))
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name="index")
]

story10/urls.py
from django.urls import path
from django.contrib.auth import views as auth 
from . import views

app_name = 'story10'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth.LoginView.as_view(template_name='story10/login.html'), name='login'),
    path('logout/', auth.LogoutView.as_view(template_name='story10/logout.html'), name='logout'),
    path('user/', views.user, name='user'),
]

story10/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.CharField(max_length=1000, default="https://www.pngitem.com/pimgs/m/129-1290719_drawn-face-meme-funny-meme-face-png-transparent.png")
    fname = models.CharField(max_length=20, default="")
    lname = models.CharField(max_length=20, default="")

    def __str__(self):
        return f"{self.user.username}'s Profile"

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs): 
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_profile(sender, instance, created, **kwargs): 
    instance.profile.save()

story10/forms.py
from django import forms
from crispy_forms.helper import FormHelper

from .models import Profile

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user']
        widgets = {
            'image': forms.TextInput(
				attrs={
                    'class': 'form-control',
                    'id': 'image',
                    'placeholder': 'Paste an image URL',
					}
				),
            'fname': forms.TextInput(
				attrs={
                    'class': 'form-control',
                    'id': 'fname',
                    'placeholder': 'Enter your first name',
					}
				),
            'lname': forms.TextInput(
				attrs={
                    'class': 'form-control',
                    'id': 'lname',
                    'placeholder': 'Enter your last name',
					}
				),
        }
    
    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.fields['image'].label = "New profile picture"
        self.fields['fname'].label = "First Name"
        self.fields['lname'].label = "Last Name"

story10/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

from story7.models import snippet
from .forms import EditProfileForm

import random

# Create your views here.
def index(request): 
    snippet.sort()
    context = {
        'snippets': snippet
    }
    return render(request, 'story10/index.html', context)

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            uname = form.cleaned_data.get('username')
            messages.add_message(request, messages.SUCCESS, f'Successfully registered {uname}. You can now log in.')
            return redirect('story10:login')
    else:
        form = UserCreationForm()

    context = {
        'form': form
    }
    return render(request, 'story10/signup.html', context)

@login_required
def user(request):    
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, f'Successfully updated profile.')
            return redirect('story10:user')    
    else: 
        form = EditProfileForm(instance=request.user.profile)

    snippet.sort()
    context = {
        'snippets': snippet,
        'form': form
    }
    return render(request, 'story10/user.html', context)

templates/story10/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}That's All I Ask of You | Story10{% endblock %}

{% block heading %}
<h1>Let the dream begin,</h1>
<h4 class="mb-3">let your darker side give in.</h4>

{% if user.is_authenticated %}
    <a id="profileButton" href="{% url 'story10:user' %}" type="button" class="btn btn-dark">Profile</a>
    <a id="logoutButton" href="{% url 'story10:logout' %}" type="button" class="btn btn-outline-dark">Log Out</a>
{% else %}
    <a id="loginButton" href="{% url 'story10:login' %}" type="button" class="btn btn-dark">Log In</a>
    <a id="signupButton" href="{% url 'story10:signup' %}" type="button" class="btn btn-outline-dark">Sign Up Now</a>
{% endif %}

{% endblock %}

{% block body %}
{% if user.is_authenticated %}
    <div class="d-flex flex-row flex-wrap justify-content-around">
        {% for snippet in snippets %}    
            <p class="m-3" style="color: {% cycle 'darksalmon' 'bisque' 'peachpuff' 'lightsalmon' 'lemonchiffon' 'khaki' %};">
                {% for line in snippet %}
                    {{ line }} <br>
                {% endfor %}
            </p>
        {% endfor %}
    </div>
{% endif %}
{% endblock %}

templates/story10/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}That's All I Ask of You{% endblock %}

{% block heading %}Log In{% endblock %}

{% block body %}
<div class="card signup p-4 mx-auto mb-5">
    <div class="signupform">    
        <form class="d-flex flex-column justify-content-center" action="" method="POST">        
            {% csrf_token %}
            <legend class="text-center lyrics">Where in the world<br> have you been hiding?</legend>
            {{ form|crispy }}
            <button id="loginButton" class="btn btn-dark mb-3 w-50 align-self-center" type="submit">Login</button>
        </form>
    </div>
    <div class="instead card-footer text-center">
        <small>
            Don't have an account? <a href="{% url 'story10:signup' %}" class="btn btn-sm btn-outline-dark ml-2">Sign Up</a>
        </small>
    </div>
</div>
{% endblock %}

templates/story10/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}That's All I Ask of You{% endblock %}

{% block heading %}Log out{% endblock %}

{% block body %}
<div class="card signup p-4 mx-auto mb-5">
    <h2 class="lyrics">Say the words<br> 
        and I will follow you.</h2>
    <h4>You are now logged out.</h4>
    <p>Thank you for trying the user auth feature.</p>
    <div class="instead card-footer text-center">
        <small>
            Log in again <a href="{% url 'story10:login' %}" class="btn btn-sm btn-outline-dark ml-2">Log in</a>
        </small>
    </div>
</div>
{% endblock %}

templates/story10/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}That's All I Ask of You{% endblock %}

{% block heading %}Sign Up{% endblock %}

{% block body %}
<div class="card signup p-4 mx-auto mb-5">
    <div class="signupform">    
        <form class="d-flex flex-column justify-content-center" action="" method="POST">        
            {% csrf_token %}
            <legend class="text-center lyrics">
                Start a journey</br>
                to a strange new world,
            </legend>
            <h5 class="text-center">Sign Up Now</h5>
            {{ form|crispy }}
            <button id="signupButton"class="btn btn-dark mb-3 w-50 align-self-center" type="submit">Sign Up</button>
        </form>
    </div>
    <div class="instead card-footer text-center">
        <small>
            Already have an account? <a href="{% url 'story10:login' %}" class="btn btn-sm btn-outline-dark ml-2">Log In</a>
        </small>
    </div>
</div>

{% endblock %}

templates/story10/user.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}That's All I Ask of You{% endblock %}

{% block heading %}
<img src="{{ user.profile.image }}" alt="profilePic" style="border-radius: 100%; width: 200px; height: 200px;">
<h1 id="greetings">Hi there, {{ user.username }}. </h1>
<h4>What a beautiful name.</h4>
<div id="editProfile" data-toggle="modal" data-target="#edit" type="button" class="btn btn-outline-dark">Edit Profile</div>
<a id="logoutButton" href="{% url 'story10:logout' %}" type="button" class="btn btn-dark">Log Out</a>
{% endblock %}

{% block body %}
{% if user.profile.fname != "" %}
    <p id="fullname" class="text-center">So your name is {{ user.profile.fname }} {{ user.profile.lname }}? Wonderful. </p>
{% endif %}
<p class="text-center" style="opacity: .1;">Enjoy these text lyrics while you're here. They're from The Phantom of The Opera. I'm kinda obsessed, so sorry not sorry.</p>
    <div class="d-flex flex-row flex-wrap justify-content-around">
        {% for snippet in snippets %}    
            <p class="m-3" style="color: {% cycle 'darksalmon' 'bisque' 'peachpuff' 'lightsalmon' 'lemonchiffon' 'khaki' %};">
                {% for line in snippet %}
                    {{ line }} <br>
                {% endfor %}
            </p>
        {% endfor %}
    </div>

<!-- Modal -->
<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" style="color: black;">Edit User Profile</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{% url 'story10:user' %}" method="POST" style="color: black;">
        <div class="modal-body">            
                {% csrf_token %}
                {{ form|crispy }}                        
        </div>
        <div class="modal-footer">
            <button id="saveEdit" type="submit" class="btn btn-dark mr-2">Save</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
        </form> 
      </div>
    </div>
  </div>
<!-- End Modal -->
{% endblock %}