stories/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views 

import story1.urls as story1
import story4.urls as story4
import story5.urls as story5
import story6.urls as story6
import story7.urls as story7
import story8.urls as story8
import story9.urls as story9
import story10.urls as story10

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('story1/', include(story1, namespace='story1')),
    path('story4/', include(story4, namespace='story4')),
    path('story5/', include(story5, namespace='story5')),
    path('story6/', include(story6, namespace='story6')),
    path('story7/', include(story7, namespace="story7")),
    path('story8/', include(story8, namespace="story8")),
    path('story9/', include(story9, namespace="story9")),
    path('story10/', include(story10, namespace="story10"))
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name="index")
]

templates/base.html
<!DOCTYPE html>
<html lang="en" class="dark">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>    
    <link rel="shortcut icon" href="{% static 'logo-dark.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <script defer src="https://use.fontawesome.com/releases/v5.13.0/js/all.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.13.0/js/v4-shims.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>    
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block style %}{% endblock %}
</head>

<body>
    {% if messages %}
    <ul class="messages container mt-4 mb-0" style="list-style: none;">
        {% for message in messages %}
        <li {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show"{% endif %}>{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    <nav class="navbar navbar-expand-lg navbar-dark sticky-top" style="background: #111; border-bottom: 2px solid black;">
        <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">Litha's PPW Stories</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ininavbar" aria-controls="ininavbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" style="flex-grow:initial;" id="ininavbar">
            <div class="navbar-nav">
                <a class="nav-link nav-item" href="{% url 'story1:index' %}">Story 1</a>
                <a class="nav-link nav-item" href="{% url 'story4:index' %}">Story 4</a>
                <a class="nav-link nav-item" href="{% url 'story5:index' %}">Story 5</a>
                <a class="nav-link nav-item" href="{% url 'story6:index' %}">Story 6</a>
                <a class="nav-link nav-item" href="{% url 'story7:index' %}">Story 7</a>
                <a class="nav-link nav-item" href="{% url 'story8:index' %}">Story 8</a>
                <a class="nav-link nav-item" href="{% url 'story9:index' %}">Story 9</a>
                <a class="nav-link nav-item" href="{% url 'story10:index' %}">Story 10</a>
            </div>
            </div>
        </div>
      </nav>
    
    <div class="container">
        <div class="header text-center">
            {% block heading %}{% endblock %}
        </div>
        {% block body %}{% endblock %}
    </div>
</body>

{% block script %} {% endblock %}
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}PPW Stories Litha{% endblock %}

{% block heading %}
<h1>PPW Stories</h1> 
{% endblock %}

{% block body %}
Hello world
{% endblock %}