stories/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views 

import story1.urls as story1
import story4.urls as story4
import story5.urls as story5
import story6.urls as story6
import story7.urls as story7
import story8.urls as story8
import story9.urls as story9
import story10.urls as story10

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('story1/', include(story1, namespace='story1')),
    path('story4/', include(story4, namespace='story4')),
    path('story5/', include(story5, namespace='story5')),
    path('story6/', include(story6, namespace='story6')),
    path('story7/', include(story7, namespace="story7")),
    path('story8/', include(story8, namespace="story8")),
    path('story9/', include(story9, namespace="story9")),
    path('story10/', include(story10, namespace="story10"))
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name="index")
]

story6/urls.py
from django.urls import path
from . import views

app_name = "story6"

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<str:nama>', views.detail, name='detail'),
    path('addPeserta/<int:id>/<str:origin>', views.addPeserta, name='addPeserta'),
    path('delPeserta/<int:id>/<int:pk>/<str:origin>', views.delPeserta, name='delPeserta'),
    path('detailPeserta/<str:nama>', views.detailPeserta, name='detailPeserta'),
    path('addKegiatan/<int:id>/<str:origin>', views.addKegiatan, name='addKegiatan')
]

story6/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Peserta(models.Model):
    nama = models.CharField(max_length=20, unique=True)
    
    def __str__(self):
        return self.nama


    def get_absolute_url(self):
        urlnama = self.nama.replace(" ", "-")
        return reverse('story6:detailPeserta', args=[str(urlnama)])

class Kegiatan(models.Model):
    nama = models.CharField(max_length=20, unique=True)
    peserta = models.ManyToManyField(Peserta, blank=True)

    def __str__(self):
        return self.nama

    def get_absolute_url(self):
        urlnama = self.nama.replace(" ", "-")
        return reverse('story6:detail', args=[str(urlnama)])

story6/forms.py
from django.forms import ModelForm
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Peserta, Kegiatan

class PesertaForm(ModelForm): 
    class Meta: 
        model = Peserta
        fields = '__all__'
        labels = {
            'nama': _('Add Peserta'),
        }
        widgets = {
            'nama': forms.TextInput(
				attrs={
					'class': 'form-control',
                    'placeholder': 'Nama Peserta',
					}
				)
        }

class KegiatanForm(ModelForm): 
    class Meta: 
        model = Kegiatan
        fields = ('nama',)
        labels = {
            'nama': _(''),
        }        
        widgets = {
            'nama': forms.TextInput(
				attrs={
					'class': 'form-control',
                    'placeholder': 'Event name',
					}
				)
        }

story6/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from .models import Kegiatan, Peserta
from .forms import PesertaForm, KegiatanForm

# Create your views here.
def index(request):  
    kegiatan = Kegiatan.objects.all()
    add_peserta = PesertaForm(request.POST or None)
    add_kegiatan = KegiatanForm(request.POST or None)
    if add_peserta.is_valid():
        add_peserta.save()
        add_peserta = PesertaForm()
    
    if add_kegiatan.is_valid():
        add_kegiatan.save()
        add_kegiatan = KegiatanForm()

    count = 3
    for i in kegiatan: 
        count += 1
    masonry_height = count // 3 * 500

    context = {
        'kegiatan': kegiatan,
        'add_peserta': add_peserta,
        'add_kegiatan': add_kegiatan,
        'height': masonry_height
    }
    return render(request, 'story6/index.html', context)

def detail(request, nama): 
    nama = nama.replace("-"," ")
    kegiatan = Kegiatan.objects.get(nama=nama)
    add_peserta = PesertaForm(request.POST or None)
    if add_peserta.is_valid():
        add_peserta.save()
        add_peserta = PesertaForm()

    context = {
        'kegiatan': kegiatan,
        'add_peserta': add_peserta
    }
    return render(request, 'story6/detail.html', context)

def addKegiatan(request, id, origin):
    if request.method == 'POST':
        if origin == 'index':
            kegiatan = request.POST['nama']

            new, status = Kegiatan.objects.get_or_create(nama=kegiatan)
            if status: 
                # kegiatan belum pernah ada
                new.save()
                messages.add_message(request, messages.SUCCESS, "{} is successfully created.".format(new))
            else: 
                # kegiatan sudah ada
                messages.add_message(request, messages.WARNING, "{} already exists.".format(new))
                
            return redirect(reverse('story6:detail', args=[new.nama]))
        
        elif origin == 'detailPeserta':
            peserta = Peserta.objects.get(id=id)
            kegiatan = request.POST['nama']

            new, status = Kegiatan.objects.get_or_create(nama=kegiatan)
            if status: 
                # add peserta baru ke kegiatan
                new.save()
                peserta.kegiatan_set.add(new)
                messages.add_message(request, messages.SUCCESS, "{} is now participating in {}".format(peserta, new))
            else: 
                try: 
                    # peserta lama udah ada di kegiatan
                    peserta.kegiatan_set.get(nama=new)
                    messages.add_message(request, messages.WARNING, "{} was already participating in {}".format(peserta, new))
                except: 
                    # peserta lama belom ada di kegiatan
                    peserta.kegiatan_set.add(new)
                    messages.add_message(request, messages.SUCCESS, "{} is now participating in {}".format(peserta, new))
            
            return redirect(reverse('story6:detailPeserta', args=[peserta.nama]))

def detailPeserta(request, nama): 
    nama = nama.replace("-"," ")
    peserta = Peserta.objects.get(nama=nama)
    add_kegiatan = KegiatanForm(request.POST or None)
    if add_kegiatan.is_valid():
        add_kegiatan.save()
        add_kegiatan = KegiatanForm()

    context = {
        'peserta': peserta,
        'add_kegiatan': add_kegiatan
    }
    return render(request, 'story6/detailPeserta.html', context)

def addPeserta(request, id, origin): 
    if request.method == 'POST':
        kegiatan = Kegiatan.objects.get(id=id)
        peserta = request.POST['nama']

        new, status = Peserta.objects.get_or_create(nama=peserta)
        if status: 
            # add peserta baru ke kegiatan
            new.save()
            kegiatan.peserta.add(new)
            messages.add_message(request, messages.SUCCESS, "{} was successfully added to {}".format(new, kegiatan.nama))
        else: 
            try: 
                # peserta lama udah ada di kegiatan
                kegiatan.peserta.get(nama=new)
                messages.add_message(request, messages.WARNING, "{} was already participating in {}".format(new, kegiatan.nama))
            except: 
                # peserta lama belom ada di kegiatan
                kegiatan.peserta.add(new)
                messages.add_message(request, messages.SUCCESS, "{} was successfully added to {}".format(new, kegiatan.nama))
    
    if origin == 'index': 
        return redirect(reverse('story6:index'))
    elif origin == 'detail': 
        return redirect(reverse('story6:detail', args=[kegiatan.nama]))

def delPeserta(request, id, pk, origin): 
    kegiatan = Kegiatan.objects.get(id=id)

    try: 
        delPeserta = get_object_or_404(Peserta, pk=pk)
        kegiatan.peserta.remove(delPeserta)
        messages.add_message(request, messages.SUCCESS, "{} successfully removed".format(delPeserta))
    except: 
        messages.add_message(request, messages.SUCCESS, "{} didn't exist".format(delPeserta))
           
    if origin == 'index': 
        return redirect(reverse('story6:index'))
    elif origin == 'detail': 
        return redirect(reverse('story6:detail', args=[kegiatan.nama]))
    

templates/story6/detail.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'story6.css' %}">
{% endblock %}

{% block title %} Detail {{kegiatan}} | Story6 {% endblock %}

{% block heading %}
<h1>{{kegiatan}} | Story6</h1>
{% endblock %}

{% block body %}
    <div class="row details">
        <div class="col-md-8">
            <h2>Details of {{kegiatan.nama}}</h2>
            <div class="mark px-3 py-2">Participants:</div>
            <ul class="mt-2 list-group list-group-flush">
                {% for peserta in kegiatan.peserta.all %}
                <li class="list-group-item d-flex justify-content-between">
                    <span>{{ peserta }}</span>
                    <a href="{% url 'story6:delPeserta' id=kegiatan.id pk=peserta.id origin='detail' %}"><i class="fa fa-trash"></i></a>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-md-4 d-flex flex-column align-items-end">
            <div class="card mb-2 w-100">
                <div class="card-header">
                    The more the merrier!
                </div>                
                <form action="{% url 'story6:addPeserta' id=kegiatan.id origin='detail' %}" method="POST" class="m-3">
                    {% csrf_token %}
                    {{ add_peserta }}
                </form>
            </div>
            <a href="{% url 'story6:index' %}" class="btn btn-dark">Go Back</a>
        </div>
    </div>

{% endblock %}

templates/story6/detailPeserta.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'story6.css' %}">
{% endblock %}

{% block title %} Detail {{peserta.nama}} | Story6 {% endblock %}

{% block heading %}
<h1>{{peserta.nama}} | Story6</h1>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-8">
            <h2>Details of {{peserta.nama}}</h2>
            <div class="mark px-3 py-2">Participating in:</div>
            <ul class="mt-2 list-group list-group-flush">
                {% for kegiatan in peserta.kegiatan_set.all %}
                <li class="list-group-item">{{ kegiatan }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-md-4 d-flex flex-column align-items-end">
            <div class="card mb-2 w-100">
                <div class="card-header">
                    Participate in more events!
                </div>
                
                <form action="{% url 'story6:addKegiatan' id=peserta.id origin='detailPeserta' %}" method="POST" class="m-3">
                    {% csrf_token %}
                    Add kegiatan:
                    {{ add_kegiatan }}
                </form>
            </div>
            <a href="{% url 'story6:index' %}" class="btn btn-dark">Go Back</a>
        </div>
    </div>
</div>

{% endblock %}

templates/story6/index.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'story6.css' %}">
{% endblock %}

{% block title %} Daftar Kegiatan | Story6 {% endblock %}

{% block heading %}
<h1>Daftar Kegiatan | Story6</h1>
{% endblock %}

{% block body %}
    <div class="card-columns">
    {% for keg in kegiatan %}
        <div class="card">
            <div class="card-header text-center">
                <a href="{{keg.get_absolute_url}}">{{ keg.nama }}</a> 
            </div>
            <div class="card-body">
                <b>Peserta:</b>
                    <ul class="list-group list-group-flush mt-2">
                        {% for peserta in keg.peserta.all %}
                            <li class="list-group-item d-flex justify-content-between">
                                <a href="{{peserta.get_absolute_url}}">{{ peserta.nama }}</a>
                                <a href="{% url 'story6:delPeserta' id=keg.id pk=peserta.id origin='index' %}"><i class="fa fa-trash"></i></a>
                            </li>                                                     
                        {% endfor%}
                    </ul>
            </div>
            <div class="card-footer">
                <form action="{% url 'story6:addPeserta' id=keg.id origin='index' %}" method="POST">
                    {% csrf_token %}
                    <b>{{ add_peserta }}</b>
                </form>
            </div>
            
        </div> 
    {% endfor %}
        <div class="card">
            <div class="card-header new text-center">
                <b>Add New Event</b>
            </div>
            <div class="card-body">
                <form 
                    action="{% url 'story6:addKegiatan' id='0' origin='index' %}" 
                    method="POST"
                    class="d-flex flex-column align-items-end">
                    {% csrf_token %}
                    {{ add_kegiatan }}
                    <input type="submit" class="btn btn-dark mt-3">
                </form>
            </div>
        </div>
    </div>

{% endblock %}